# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore ./ElectronicDiary.Domain/ElectronicDiary.Domain.csproj

      # Сборка проекта
      - name: Build
        run: dotnet build ./ElectronicDiary.Domain/ElectronicDiary.Domain.csproj --configuration Release

      # Запуск тестов
      - name: Run tests
        run: dotnet test ./ElectronicDiary.Tests/ElectronicDiary.Tests.csproj --configuration Release
